# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Install dependencies required for OpenCV's GUI features
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libfontconfig1 \
    ffmpeg \
    xvfb \
 && rm -rf /var/lib/apt/lists/*

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir numpy opencv-python ffmpeg-python

# Make port 2300 available to the world outside this container
EXPOSE 2300/udp

# Set a default command or entrypoint that starts Xvfb
CMD python deployment_udp_client.py